export * from "./cliente.interface";
export * from "./duenonegocio.interface";
export * from "./historial.interface";
export * from "./inventario.interface";
export * from "./lote.interface";
export * from "./negocio.interface";
export * from "./orden.interface";
export * from "./product.interface";
export * from "./user.interface";
